# Generated by Django 3.2.6 on 2021-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ['id'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Quiz Title'),
        ),
    ]
